{% set name = "neighpy" %}
{% set version = "0.1.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/neighpy-{{ version }}.tar.gz
  sha256: 4f663d3d122df3e95f3113a1e636b3524eb88f29de3bcf1810145644cbac0617

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - poetry-dynamic-versioning >=1.0.0,<2.0.0
    - pip
  run:
    - python >={{ python_min }},<4.0.0
    - numpy >=1.22
    - joblib >=1.3.2,<2.0.0
    - tqdm >=4.66.2,<5.0.0

test:
  imports:
    - neighpy
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/auggiemarignier/neighpy
  summary: Neighbourhood Algorithm in Python
  license: GPL-3.0-or-later
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - auggiemarignier
