{% set name = "neighpy" %}
{% set version = "0.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/neighpy-{{ version }}.tar.gz
  sha256: 6f1c4f82b1c463c8a3ab7cabb7d742a4caa6654d2ff443cae82293aa3b9815d7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core >=1.0.0
    - poetry-dynamic-versioning >=1.0.0,<2.0.0
    - pip
  run:
    - python >=3.8.0,<4.0.0
    - numpy >=1.22
    - joblib >=1.3.2,<2.0.0
    - tqdm >=4.66.2,<5.0.0

test:
  imports:
    - neighpy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/auggiemarignier/neighpy
  summary: Neighbourhood Algorithm in Python
  license: GPL-3.0-or-later
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - auggiemarignier
